#!/usr/bin/env bash
set -euo pipefail

# Mount local Career-Ops subfolders as separate Finder-visible NFS volumes.
# Uses macOS built-in nfsd — no macFUSE or bindfs required.
# Installs a LaunchDaemon so mounts survive reboots automatically.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_ROOT="${SRC_ROOT:-$SCRIPT_DIR}"
OWNER="${OWNER:-$(id -un)}"
ROOT_SLASH="/"
OWNER_HOME="${OWNER_HOME:-$(dscl . -read "${ROOT_SLASH}Users/$OWNER" NFSHomeDirectory 2>/dev/null | awk '{print $2}')}"
OWNER_HOME="${OWNER_HOME:-$HOME}"
OWNER_UID="$(id -u "$OWNER")"
TAILSCALE_NET="100.64.0.0"
TAILSCALE_MASK="255.192.0.0"

BOOT_SCRIPT=/usr/local/bin/career-ops-nfs-mount.sh
PLIST=${PLIST:-/Library/LaunchDaemons/com.example.career-ops-mounts.plist}

MOUNTS=(
  "career-ops-images:images"
  "career-ops-interview-prep:interview-prep"
  "career-ops-notes:notes"
  "career-ops-output:output"
)

[[ $EUID -eq 0 ]] || { echo "Run with sudo: sudo bash $0" >&2; exit 1; }

if [[ ! -d "$SRC_ROOT" ]]; then
  echo "Missing source folder: $SRC_ROOT" >&2; exit 1
fi

# ---------- /etc/exports ----------
configure_nfsd() {
  local tmp; tmp=$(mktemp)

  [[ -f /etc/exports ]] && grep -v "career-ops" /etc/exports > "$tmp" || true

  for entry in "${MOUNTS[@]}"; do
    local subdir="${entry#*:}"
    local src="$SRC_ROOT/$subdir"
    [[ -d "$src" ]] || { echo "WARNING: Missing $src — skipping" >&2; continue; }
    printf '"%s" -alldirs -mapall=%s 127.0.0.1\n' "$src" "$OWNER" >> "$tmp"
    printf '"%s" -alldirs -mapall=%s -network %s -mask %s\n' \
      "$src" "$OWNER" "$TAILSCALE_NET" "$TAILSCALE_MASK" >> "$tmp"
  done

  cp "$tmp" /etc/exports; rm "$tmp"
  nfsd checkexports || { echo "exports validation failed" >&2; exit 1; }

  if nfsd status 2>/dev/null | grep -q "is running"; then
    nfsd restart
  else
    nfsd enable
    nfsd start
  fi
  echo "nfsd configured and running"
}

# ---------- boot mount script ----------
install_boot_script() {
  cat > "$BOOT_SCRIPT" <<SCRIPT
#!/usr/bin/env bash
# Auto-generated by install-career-ops-finder-mounts.sh — do not edit manually
SRC_ROOT=$SRC_ROOT
OWNER=$OWNER
OWNER_UID=$OWNER_UID
OWNER_HOME=$OWNER_HOME

mount_share() {
  local dst="\$1" src="\$2"
  mkdir -p "\$dst"
  mount | grep -Fq " on \$dst " && return 0
  # Retry a few times — nfsd may still be starting
  for i in 1 2 3 4 5; do
    mount_nfs -o resvport,soft,locallocks "127.0.0.1:\$src" "\$dst" 2>/dev/null && return 0
    sleep 2
  done
  echo "Failed to mount \$dst" >&2
  return 1
}

SCRIPT

  for entry in "${MOUNTS[@]}"; do
    local name="${entry%%:*}"
    local subdir="${entry#*:}"
    printf 'mount_share "%s/%s" "%s/%s"\n' \
      "$OWNER_HOME" "$name" "$SRC_ROOT" "$subdir" >> "$BOOT_SCRIPT"
  done

  chmod +x "$BOOT_SCRIPT"
  echo "Installed boot script: $BOOT_SCRIPT"
}

# ---------- LaunchDaemon plist ----------
install_launchdaemon() {
  cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.example.career-ops-mounts</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$BOOT_SCRIPT</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>StandardOutPath</key>
  <string>/var/log/career-ops-mounts.log</string>
  <key>StandardErrorPath</key>
  <string>/var/log/career-ops-mounts.log</string>
  <key>AfterSystemStart</key>
  <true/>
</dict>
</plist>
PLIST

  chown root:wheel "$PLIST"
  chmod 644 "$PLIST"

  # Load/reload the daemon
  launchctl unload "$PLIST" 2>/dev/null || true
  launchctl load -w "$PLIST"
  echo "LaunchDaemon installed and loaded: $PLIST"
}

# ---------- main ----------
configure_nfsd
install_boot_script
install_launchdaemon

# Run the mounts now (don't wait for reboot)
bash "$BOOT_SCRIPT"

echo
echo "Career-Ops Finder mounts:"
mount | grep -E 'career-ops-(images|interview-prep|notes|output)' || echo "(none active)"
echo
echo "Remote clients can mount via your private network or VPN:"
for entry in "${MOUNTS[@]}"; do
  local subdir="${entry#*:}"
  printf "  sudo mount_nfs -o resvport,soft ${REMOTE_NFS_HOST:-100.64.0.1}:%s/%s /mountpoint\n" \
    "$SRC_ROOT" "$subdir"
done
